on:
  push:

jobs:
  restore:
    strategy:
      matrix:
        dotnet-version: [3.1.100, 3.1.101]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - run: dotnet --version
      - run: dotnet new console
      - run: dotnet add package NuGet.Packaging
      - run: |
          dotnet restore --packages packages --source https://api.nuget.org/v3/index.json --force
          ls packages
