on:
  push:

jobs:
  restore:
    strategy:
      matrix:
        dotnet-version: [3.1.301, 3.1.200, 3.1.101, 3.0.100]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: dotnet tool install --tool-path tools gpr
      - run: dotnet new globaljson --sdk-version ${{ matrix.dotnet-version }}
      - run: dotnet --version
      - run: dotnet new console
      - run: dotnet add package NuGet.Packaging
      - run: |
          dotnet restore --packages packages --source https://api.nuget.org/v3/index.json --force --use-lock-file
          ls packages
      - run: cat packages.lock.json
        
